-- chunkname: @/modules/game_shaders/shaders.lua

function init()
	g_shaders.createOutfitShader(ShaderLightBlue, "/shaders/outline/outline_vertex", "/shaders/outline/outline_light_blue_fragment")
	g_shaders.createOutfitShader(ShaderBlue, "/shaders/outline/outline_vertex", "/shaders/outline/outline_blue_fragment")
	g_shaders.createOutfitShader(ShaderRed, "/shaders/outline/outline_vertex", "/shaders/outline/outline_red_fragment")
	g_shaders.createOutfitShader(ShaderDarkRed, "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_red_fragment")
	g_shaders.createOutfitShader(ShaderPurple, "/shaders/outline/outline_vertex", "/shaders/outline/outline_purple_fragment")
	g_shaders.createOutfitShader(ShaderWhite, "/shaders/outline/outline_vertex", "/shaders/outline/outline_white_fragment")
	g_shaders.createOutfitShader(ShaderDarkGreen, "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_green_fragment")
	g_shaders.createOutfitShader(ShaderForestGreen, "/shaders/outline/outline_vertex", "/shaders/outline/outline_forest_green_fragment")
	g_shaders.createOutfitShader(ShaderMud, "/shaders/outline/outline_vertex", "/shaders/outline/outline_mud_fragment")
	g_shaders.createOutfitShader(ShaderLightBlueStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_light_blue_static_fragment")
	g_shaders.createOutfitShader(ShaderBlueStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_blue_static_fragment")
	g_shaders.createOutfitShader(ShaderRedStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_red_static_fragment")
	g_shaders.createOutfitShader(ShaderDarkRedStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_red_static_fragment")
	g_shaders.createOutfitShader(ShaderPurpleStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_purple_static_fragment")
	g_shaders.createOutfitShader(ShaderWhiteStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_white_static_fragment")
	g_shaders.createOutfitShader(ShaderRage, "/shaders/outline/outline_vertex", "/shaders/outline/rage_shader")
	g_shaders.createOutfitShader(ShaderFreeze, "/shaders/outline/outline_vertex", "/shaders/outline/freeze_shader")
	g_shaders.createOutfitShader(ShaderGreen, "/shaders/outline/outline_vertex", "/shaders/outline/outline_green_fragment")
	g_shaders.createOutfitShader(ShaderGreenStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_green_static_fragment")
	g_shaders.createOutfitShader(ShaderYellow, "/shaders/outline/outline_vertex", "/shaders/outline/outline_yellow_fragment")
	g_shaders.createOutfitShader(ShaderYellowStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_yellow_static_fragment")
	g_shaders.createOutfitShader(ShaderCreatureHighlight, "/shaders/outline/outline_vertex", "/shaders/outline/creature_highlight")
	g_shaders.createOutfitShader(ShaderGreenOutfit, "/shaders/outline/outline_vertex", "/shaders/outline/green_outfit")
	g_shaders.createOutfitShader(ShaderPurpleOutfit, "/shaders/outline/outline_vertex", "/shaders/outline/purple_outfit")
	g_shaders.createOutfitShader(ShaderDarkGreenStatic, "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_green_static_fragment")
	g_shaders.createOutfitShader(WeaponShader1, "/shaders/outline/weapon_vertex", "/shaders/outline/weapon_shader_1")
	g_shaders.createOutfitShader(WeaponShader2, "/shaders/outline/weapon_vertex", "/shaders/outline/weapon_shader_2")
	g_shaders.createOutfitShader(WeaponShader3, "/shaders/outline/weapon_vertex", "/shaders/outline/weapon_shader_3")
	g_shaders.createShader(ShaderMapLightFog, "/shaders/map/map_light_fog_vertex", "/shaders/map/map_light_fog_fragment")
	g_shaders.addTexture(ShaderMapLightFog, "/shaders/map/textures/light_fog.png")
	g_shaders.createShader(ShaderMapHeavyFog, "/shaders/map/map_heavy_fog_vertex", "/shaders/map/map_heavy_fog_fragment")
	g_shaders.addTexture(ShaderMapHeavyFog, "/shaders/map/textures/heavy_fog.png")
	g_shaders.createShader(ShaderMapLightRain, "/shaders/map/map_light_rain_vertex", "/shaders/map/map_light_rain_fragment")
	g_shaders.addTexture(ShaderMapLightRain, "/shaders/map/textures/light_rain.png")
	g_shaders.addTexture(ShaderMapLightRain, "/shaders/map/textures/light_fog.png")
	g_shaders.createShader(ShaderMapHeavyRain, "/shaders/map/map_heavy_rain_vertex", "/shaders/map/map_heavy_rain_fragment")
	g_shaders.addTexture(ShaderMapHeavyRain, "/shaders/map/textures/heavy_rain.png")
	g_shaders.addTexture(ShaderMapHeavyRain, "/shaders/map/textures/heavy_fog.png")
	g_shaders.createShader(ShaderMapHeavyRainLightning, "/shaders/map/map_heavy_rain_lightning_vertex", "/shaders/map/map_heavy_rain_lightning_fragment")
	g_shaders.addTexture(ShaderMapHeavyRainLightning, "/shaders/map/textures/heavy_rain.png")
	g_shaders.addTexture(ShaderMapHeavyRainLightning, "/shaders/map/textures/heavy_fog.png")
	g_shaders.addTexture(ShaderMapHeavyRainLightning, "/shaders/map/textures/lightning.png")
	g_shaders.createShader(ShaderMapLightSandstorm, "/shaders/map/map_light_sandstorm_vertex", "/shaders/map/map_light_sandstorm_fragment")
	g_shaders.addTexture(ShaderMapLightSandstorm, "/shaders/map/textures/light_sandstorm.png")
	g_shaders.addTexture(ShaderMapLightSandstorm, "/shaders/map/textures/sand_fog.png")
	g_shaders.createShader(ShaderMapHeavySandstorm, "/shaders/map/map_heavy_sandstorm_vertex", "/shaders/map/map_heavy_sandstorm_fragment")
	g_shaders.addTexture(ShaderMapHeavySandstorm, "/shaders/map/textures/heavy_sandstorm.png")
	g_shaders.addTexture(ShaderMapHeavySandstorm, "/shaders/map/textures/sand_fog.png")
	g_shaders.createShader(ShaderMapLightSandstormDistortion, "/shaders/map/map_light_sandstorm_vertex", "/shaders/map/map_light_sandstorm_distortion_fragment")
	g_shaders.addTexture(ShaderMapLightSandstormDistortion, "/shaders/map/textures/light_sandstorm.png")
	g_shaders.createShader(ShaderMapHeavySandstormDistortion, "/shaders/map/map_heavy_sandstorm_vertex", "/shaders/map/map_heavy_sandstorm_distortion_fragment")
	g_shaders.addTexture(ShaderMapHeavySandstormDistortion, "/shaders/map/textures/heavy_sandstorm.png")
	g_shaders.createShader(ShaderMapDistortion, "/shaders/map/map_default_vertex", "/shaders/map/map_distortion_fragment")
	g_shaders.createShader(ShaderMapLightSnow, "/shaders/map/map_light_snow_vertex", "/shaders/map/map_light_snow_fragment")
	g_shaders.addTexture(ShaderMapLightSnow, "/shaders/map/textures/light_snow.png")
	g_shaders.addTexture(ShaderMapLightSnow, "/shaders/map/textures/light_fog.png")
	g_shaders.createShader(ShaderMapHeavySnow, "/shaders/map/map_heavy_snow_vertex", "/shaders/map/map_heavy_snow_fragment")
	g_shaders.addTexture(ShaderMapHeavySnow, "/shaders/map/textures/heavy_snow.png")
	g_shaders.addTexture(ShaderMapHeavySnow, "/shaders/map/textures/light_fog.png")
	g_shaders.createShader(ShaderMapSepia, "/shaders/map/map_default_vertex", "/shaders/map/map_filter_sepia")
	g_shaders.createShader(ShaderWidgetGlow, "/shaders/widget/widget_default_vertex", "/shaders/widget/pepega")
	g_shaders.createShader(ShaderAetherEnhancement, "/shaders/effects/aether_enhancement_vertex", "/shaders/effects/aether_enhancement_fragment", true)
end

function terminate()
	return
end
